Merge minor patch rules
DanaePlays/mlox-rules pull request #109
Opened 2023-05-22 12:51 UTC by MasssiveJuice08

Minor patch rules added for "Morag Tong Polished", "Magical Missions" and "Privileges and Services"

2023-05-22 13:14 UTC, rfuzzo requested changes

2023-05-22 13:14 UTC, rfuzzo commented on mlox_user.txt
> +Morag Tong Polished.esp
that's already at line 4552

2023-05-22 23:11 UTC, MasssiveJuice08 commented on mlox_user.txt
> +Morag Tong Polished.esp
Oh look, now it isn't 😅

2023-05-23 04:24 UTC, rfuzzo approved these changes
Magically, the old rule has disappeared 🤨 Approving now.

2023-05-23 04:25 UTC, merged